package com.oasisdrinks.app.views;



/**
 *
 * @author Grupo 3
 */
public class Consultar extends javax.swing.JFrame {
Frmsistema objFrmsistema = new Frmsistema();
    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Consulta de Gaseosas");
        CBOMARCA.addItem(objFrmsistema.marca0);
        CBOMARCA.addItem(objFrmsistema.marca1);
;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LBLPRECIO = new javax.swing.JLabel();
        LBLCONTENIDO = new javax.swing.JLabel();
        LBLPESO = new javax.swing.JLabel();
        LBLSABOR = new javax.swing.JLabel();
        CBOMARCA = new javax.swing.JComboBox<>();
        BTNCERRA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Marca");

        jLabel2.setText("Precio (S/)");

        jLabel3.setText("Contenido (uni.)");

        jLabel4.setText("Peso (gr.)");

        jLabel5.setText("Sabor");

        LBLPRECIO.setText("jLabel6");

        LBLCONTENIDO.setText("jLabel6");

        LBLPESO.setText("jLabel6");

        LBLSABOR.setText("jLabel6");

        CBOMARCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOMARCAActionPerformed(evt);
            }
        });

        BTNCERRA.setText("Cerrar");
        BTNCERRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCERRAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLSABOR)
                            .addComponent(LBLPESO)
                            .addComponent(LBLPRECIO)
                            .addComponent(CBOMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBLCONTENIDO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(BTNCERRA)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBOMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LBLPRECIO))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LBLCONTENIDO)
                    .addComponent(BTNCERRA))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LBLPESO))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LBLSABOR))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCERRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCERRAActionPerformed
        // TODO add your handling code here:
        objFrmsistema.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNCERRAActionPerformed

    private void CBOMARCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOMARCAActionPerformed
        // TODO add your handling code here:
        if (CBOMARCA.getSelectedItem()==objFrmsistema.marca0)
        {
            LBLPRECIO.setText(Double.toString(Frmsistema.precio0));
            LBLCONTENIDO.setText(Integer.toString(Frmsistema.contenido0));
            LBLPESO.setText(Double.toString(Frmsistema.peso0));
            LBLSABOR.setText(Frmsistema.sabor0);
        }
        else 
            if (CBOMARCA.getSelectedItem()==objFrmsistema.marca1)
            {
               LBLPRECIO.setText(Double.toString(Frmsistema.precio1));
               LBLCONTENIDO.setText(Integer.toString(Frmsistema.contenido1));
               LBLPESO.setText(Double.toString(Frmsistema.peso1));
               LBLSABOR.setText(Frmsistema.sabor1); 
            }
    }//GEN-LAST:event_CBOMARCAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCERRA;
    private javax.swing.JComboBox<String> CBOMARCA;
    private javax.swing.JLabel LBLCONTENIDO;
    private javax.swing.JLabel LBLPESO;
    private javax.swing.JLabel LBLPRECIO;
    private javax.swing.JLabel LBLSABOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
