package com.oasisdrinks.app.views;



/**
 *
 * @author Grupo 3
 */
public class Listar extends javax.swing.JFrame {
Frmsistema objFrmsistema = new Frmsistema();
    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Listar Bebidas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TXTAREALISTAR = new javax.swing.JTextArea();
        BTNCERRAR = new javax.swing.JButton();
        BTNLISTAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTAREALISTAR.setColumns(20);
        TXTAREALISTAR.setRows(5);
        jScrollPane1.setViewportView(TXTAREALISTAR);

        BTNCERRAR.setText("CERRAR");
        BTNCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCERRARActionPerformed(evt);
            }
        });

        BTNLISTAR.setText("LISTAR");
        BTNLISTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLISTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(BTNCERRAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNLISTAR)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNCERRAR)
                    .addComponent(BTNLISTAR))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCERRARActionPerformed
        // TODO add your handling code here:
        objFrmsistema.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_BTNCERRARActionPerformed

    private void BTNLISTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLISTARActionPerformed
        // TODO add your handling code here:
        TXTAREALISTAR.append("Listado de Bebidas"+"\n\n");
        TXTAREALISTAR.append("Marca: "+objFrmsistema.insumo0+"\n");
        TXTAREALISTAR.append("Precio: "+objFrmsistema.precio0+"\n");
        TXTAREALISTAR.append("Contenido: "+objFrmsistema.contenido0+"\n");
        TXTAREALISTAR.append("Peso: "+objFrmsistema.peso0+"\n");
        TXTAREALISTAR.append("Sabor: "+objFrmsistema.sabor0+"\n");
        TXTAREALISTAR.append("\n\n");
        TXTAREALISTAR.append("Marca: "+objFrmsistema.insumo1+"\n");
        TXTAREALISTAR.append("Precio: "+objFrmsistema.precio1+"\n");
        TXTAREALISTAR.append("Contenido: "+objFrmsistema.contenido1+"\n");
        TXTAREALISTAR.append("Peso: "+objFrmsistema.peso1+"\n");
        TXTAREALISTAR.append("Sabor: "+objFrmsistema.sabor1+"\n");
        TXTAREALISTAR.append("\n\n");
        
    }//GEN-LAST:event_BTNLISTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCERRAR;
    private javax.swing.JButton BTNLISTAR;
    private javax.swing.JTextArea TXTAREALISTAR;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
