package com.oasisdrinks.app.views;

import com.oasisdrinks.app.models.Bebida;
import com.oasisdrinks.app.models.Insumo;
import com.oasisdrinks.app.models.InsumoLiquido;
import com.oasisdrinks.app.models.InsumoSolido;
import com.oasisdrinks.app.models.Medida;
import com.oasisdrinks.app.models.Producto;
import com.oasisdrinks.app.models.Receta;
import com.oasisdrinks.app.models.Usuario;
import com.oasisdrinks.app.utils.general.CacheUtils;
import javax.swing.JFrame;
import java.util.*;
import javax.print.attribute.standard.Media;


/**
 *
 * @author Grupo 3
 */
public class MainView extends javax.swing.JFrame {
    
    
    public static String insumo0 = "Maracuya";
    public static double precio0 = 35.0;
    public static int contenido0 = 12;
    public static double peso0 = 120;
    public static String sabor0 = "Maracuya";
    
     public static String insumo1 = "Chicha";
    public static double precio1 = 40.0;
    public static int contenido1 = 13;
    public static double peso1 = 130;
    public static String sabor1 = "Chicha";

    Map<String, List<?>> cache = new HashMap<>();


    
    // Porcentajes de descuento
public static double porcentaje1 = 3.0;
public static double porcentaje2 = 2.0;


// Cantidad óptima de lotes vendidas
public static int cantidadOptima = 20;

// Cantidad mínima de paquetes adquiridos para obtener el obsequio
public static int cantidadObsequiable = 15;
	
// Obsequio por cantidad mínima de paquetes adquiridos
public static String obsequio = "Balon de gas";

// Número de cliente que recibe el premio sorpresa
public static int numeroClienteSorpresa = 3;

// Premio sorpresa
public static String premioSorpresa = "Peluche de nuestra mascota";


    public MainView() {
        initComponents();
        initializeCache();
        this.setLocationRelativeTo(this);
        this.setTitle("Sistema de Ventas Oasis Drink");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        MNUSalir = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        MNUMantenimiento = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MNUVENDER = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MNUCONFIDES = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        MNUCONFCANTOP = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        MNUAcercade = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oasis Drinks Ventana Principal");

        MNUSalir.setText("Archivo");
        MNUSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNUSalirActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Salida");
        MNUSalir.add(jMenuItem4);

        jMenuBar1.add(MNUSalir);

        MNUMantenimiento.setText("Mantenimiento");

        jMenuItem2.setText("Consultar Bebidas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MNUMantenimiento.add(jMenuItem2);

        jMenuItem3.setText("Modificar Bebidas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MNUMantenimiento.add(jMenuItem3);

        jMenuItem1.setText("Listar Bebidas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MNUMantenimiento.add(jMenuItem1);

        jMenuItem5.setText("Insumos - Agregar y Listar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MNUMantenimiento.add(jMenuItem5);

        jMenuItem8.setText("Medidas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        MNUMantenimiento.add(jMenuItem8);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Productos");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        MNUMantenimiento.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Usuarios");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        MNUMantenimiento.add(jRadioButtonMenuItem2);

        jMenuBar1.add(MNUMantenimiento);

        jMenu4.setText("Ventas");

        MNUVENDER.setText("Vender");
        MNUVENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNUVENDERActionPerformed(evt);
            }
        });
        jMenu4.add(MNUVENDER);

        jMenuItem6.setText("Generar reportes");
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Configuración");

        MNUCONFIDES.setText("Configurar descuentos");
        MNUCONFIDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNUCONFIDESActionPerformed(evt);
            }
        });
        jMenu5.add(MNUCONFIDES);

        jMenuItem9.setText("Configurar obsequio");
        jMenu5.add(jMenuItem9);

        MNUCONFCANTOP.setText("Configurar cantidad óptima de gaseosas vendidos");
        MNUCONFCANTOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNUCONFCANTOPActionPerformed(evt);
            }
        });
        jMenu5.add(MNUCONFCANTOP);

        jMenuItem11.setText("Configurar premio sorpresa");
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        MNUAcercade.setText("Ayuda");
        MNUAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNUAcercadeActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Acerca de Tienda");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        MNUAcercade.add(jMenuItem7);

        jMenuBar1.add(MNUAcercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void initializeCache() {
        loadFakeDataToCache();
    }

    private void loadFakeDataToCache() {
        // Temp persistence
        CacheUtils cu = new CacheUtils();

        // // Initialize cache arrays
        List<Insumo> insumos = new ArrayList<>();
        List<Medida> medidas = new ArrayList<>();
        List<Producto> productos = new ArrayList<>();
        List<Receta> recetas = new ArrayList<>();

        // // Create fake objects

        // medidas.add(new Medida(1, "Kilogramos", "Kg"));
        // medidas.add(new Medida(2, "Litros", "Lt"));
        // medidas.add(new Medida(3, "Unidades", "Uni"));
        // medidas.add(new Medida(4, "Onzas", "Oz"));
        // medidas.add(new Medida(5, "Mililitros", "ml"));
        // medidas.add(new Medida(6, "Tazas", "Tza"));
        // medidas.add(new Medida(7, "Botellas", "Bot"));


        // insumos.add(new InsumoLiquido(3.4, 1, "Limones", 34, medidas.get(2), 1));

        // // Adding more InsumoLiquido objects
        // insumos.add(new InsumoLiquido(2.1, 2, "Jugo de Naranja", 20, medidas.get(1), 2));
        // insumos.add(new InsumoLiquido(1.8, 3, "Agua Mineral", 50, medidas.get(2), 3));

        // // Adding InsumoSolido objects
        // insumos.add(new InsumoSolido(4, "Azúcar", 10, medidas.get(0), 2));
        // insumos.add(new InsumoSolido(5, "Canela", 5, medidas.get(3), 0.5));

        // // Add more InsumoSolido objects
        // insumos.add(new InsumoSolido(6, "Sal", 15, medidas.get(0), 1));
        // insumos.add(new InsumoSolido(7, "Pimienta", 7, medidas.get(3), 0.23));
        // insumos.add(new InsumoSolido(8, "Comino", 8, medidas.get(3), 0.75));

        // // Add more InsumoLiquido objects
        // insumos.add(new InsumoLiquido(1.5, 9, "Leche", 30, medidas.get(1), 3.2));
        // insumos.add(new InsumoLiquido(2.3, 10, "Soda", 40, medidas.get(1), 4.5));


        // // Adding InsumoLiquido objects
        // insumos.add(new InsumoLiquido(1.2, 11, "Jugo de Manzana", 25, medidas.get(5), 11));
        // insumos.add(new InsumoLiquido(1.5, 12, "Agua de Coco", 35, medidas.get(5), 12));
        // insumos.add(new InsumoLiquido(2.7, 13, "Refresco de Maracuyá", 40, medidas.get(5), 13));

        // // Adding InsumoSolido objects
        // insumos.add(new InsumoSolido(17, "Harina", 5, medidas.get(6), 1.5));
        // insumos.add(new InsumoSolido(18, "Azúcar Glass", 3, medidas.get(4), 0.75));
        // insumos.add(new InsumoSolido(19, "Café Molido", 4, medidas.get(6), 0.5));

        // // Adding more InsumoLiquido objects
        // insumos.add(new InsumoLiquido(2.2, 14, "Agua de Horchata", 30, medidas.get(5), 20));
        // insumos.add(new InsumoLiquido(1.8, 15, "Jugo de Mango", 25, medidas.get(5), 21));
        // insumos.add(new InsumoLiquido(2.5, 16, "Refresco de Fresa", 40, medidas.get(5), 22));

        // // Adding more InsumoSolido objects
        // insumos.add(new InsumoSolido(20, "Sal Marina", 2, medidas.get(4), 0.5));
        // insumos.add(new InsumoSolido(21, "Chocolate en Polvo", 4, medidas.get(6), 0.25));
        // insumos.add(new InsumoSolido(22, "Levadura", 3, medidas.get(4), 0.8));


        // // Creating Bebida objects and adding them to the productos list
        // productos.add(new Bebida(1, "Jugo de Manzana", 100, 3, 0.2));
        // //productos.get(1).setMedida(medidas.get(1));
        // productos.add(new Bebida(2, "Agua de Coco", 50, 2, 0.25));
        // productos.add(new Bebida(3, "Refresco de Maracuyá", 75, 4, 0.15));
        // productos.add(new Bebida(4, "Té Frío de Durazno", 60, 2, 0.3));
        // productos.add(new Bebida(5, "Limonada", 80, 3, 0.2));
        // productos.add(new Bebida(6, "Cerveza Artesanal", 40, 4, 0.35));
        // productos.add(new Bebida(7, "Gaseosa de Naranja", 90, 2, 0.15));
        // productos.add(new Bebida(8, "Chicha Morada", 70, 4, 0.25));
        // productos.add(new Bebida(9, "Jugo de Mango", 50, 3, 0.2));
        // productos.add(new Bebida(10, "Agua Mineral", 120, 2, 0.1));

        // productos.forEach( prod -> prod.setMedida(medidas.get(1)) );
        // System.out.println("Productos with Medidas:\n" + productos);

        // // Add fake data to cache
        // this.cache.put("insumos", insumos);
        // this.cache.put("medidas", medidas);
        // this.cache.put("productos", productos);
        // this.cache.put("recetas", recetas);
        // cu.storeCache(cache);

        Map<String, List<?>> histCache = cu.loadCache();
        this.cache.put("insumos", (List<Insumo>) histCache.get("insumos"));
        this.cache.put("medidas", (List<Medida>) histCache.get("medidas"));
        this.cache.put("productos", (List<Producto>) histCache.get("productos"));
        this.cache.put("recetas", (List<Receta>) histCache.get("recetas"));
        this.cache.put("usuarios", (List<Usuario>) histCache.get("usuarios"));


    }

    private void MNUSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNUSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_MNUSalirActionPerformed

    private void MNUAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNUAcercadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MNUAcercadeActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        dlgAcercade objdlgAcercade = new dlgAcercade(this, rootPaneCheckingEnabled);
        objdlgAcercade.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Consultar objConsultar = new Consultar();
        objConsultar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Modificar objModificar = new Modificar();
        objModificar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MNUVENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNUVENDERActionPerformed
        // TODO add your handling code here:
        Vender objVender = new Vender();
        objVender.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MNUVENDERActionPerformed

    private void MNUCONFIDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNUCONFIDESActionPerformed
        // TODO add your handling code here:
        ConfigurarDescuento objConfigurarDescuento = new ConfigurarDescuento();
        objConfigurarDescuento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MNUCONFIDESActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Listar objListar = new Listar();
        objListar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MNUCONFCANTOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNUCONFCANTOPActionPerformed
        // TODO add your handling code here:
        ConfigurarCantidadOptima objConfigurarCantidadOptima = new ConfigurarCantidadOptima();
        objConfigurarCantidadOptima.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MNUCONFCANTOPActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        InsumoView insumoView = new InsumoView();
        // insumoView.setCache(cache);
        insumoView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        insumoView.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        MedidaView medidaView = new MedidaView();
        medidaView.setCache(cache);
        medidaView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        medidaView.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        ProductoView productoView = new ProductoView();
        productoView.setCache(cache);
        productoView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        productoView.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed

        UsuariosView usuarioView = new UsuariosView();
        usuarioView.setCache(cache);
        usuarioView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        usuarioView.setVisible(true);

    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MNUAcercade;
    private javax.swing.JMenuItem MNUCONFCANTOP;
    private javax.swing.JMenuItem MNUCONFIDES;
    private javax.swing.JMenu MNUMantenimiento;
    private javax.swing.JMenu MNUSalir;
    private javax.swing.JMenuItem MNUVENDER;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    // End of variables declaration//GEN-END:variables
}
