package com.oasisdrinks.app.views;



/**
 *
 * @author Grupo 3
 */
public class Vender extends javax.swing.JFrame {
MainView objFrmsistema = new MainView();
    /**
     * Creates new form Vender
     */
    public Vender() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Listar Bebidas");
        CBOINSUMO.addItem(objFrmsistema.insumo0);
        CBOINSUMO.addItem(objFrmsistema.insumo1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBOINSUMO = new javax.swing.JComboBox<>();
        LBLPRECIO = new javax.swing.JLabel();
        TXTCANTIDAD = new javax.swing.JTextField();
        BTNVENDER = new javax.swing.JButton();
        BTNCERRAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXTAREAVENDER = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Insumo");

        jLabel2.setText("Precio (S/)");

        jLabel3.setText("Cantidad");

        CBOINSUMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOINSUMOActionPerformed(evt);
            }
        });

        LBLPRECIO.setText("jLabel4");

        TXTCANTIDAD.setColumns(5);

        BTNVENDER.setText("VENDER");
        BTNVENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVENDERActionPerformed(evt);
            }
        });

        BTNCERRAR.setText("CERRAR");
        BTNCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCERRARActionPerformed(evt);
            }
        });

        TEXTAREAVENDER.setColumns(20);
        TEXTAREAVENDER.setRows(5);
        jScrollPane1.setViewportView(TEXTAREAVENDER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBOINSUMO, 0, 129, Short.MAX_VALUE)
                            .addComponent(TXTCANTIDAD)
                            .addComponent(LBLPRECIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNVENDER)
                            .addComponent(BTNCERRAR))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBOINSUMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNVENDER))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LBLPRECIO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(TXTCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BTNCERRAR))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCERRARActionPerformed
        // TODO add your handling code here:
        objFrmsistema.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_BTNCERRARActionPerformed

    private void CBOINSUMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOINSUMOActionPerformed
        // TODO add your handling code here:
        if (CBOINSUMO.getSelectedItem()==objFrmsistema.insumo0)
        {
            LBLPRECIO.setText(Double.toString(MainView.precio0));
        }
        else 
            if (CBOINSUMO.getSelectedItem()==objFrmsistema.insumo1)
        {
            LBLPRECIO.setText(Double.toString(MainView.precio1));
        }
    }//GEN-LAST:event_CBOINSUMOActionPerformed

    private void BTNVENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVENDERActionPerformed
        // TODO add your handling code here:
        double p, imp, dsct, pgo; //precio, importe, descuento, lo que se debe pagar
        int c; //cantidad de paquetes de bebidas vendidas
        p=Double.parseDouble(LBLPRECIO.getText());
        c=Integer.parseInt(TXTCANTIDAD.getText());
        imp=p*c;
        if (c>=1 && c<=5)
            dsct=objFrmsistema.porcentaje1/100*imp;
        else 
            dsct=objFrmsistema.porcentaje2/100*imp;
        pgo=imp-dsct;
        TEXTAREAVENDER.append("Venta de Bebidas"+"\n\n");
        TEXTAREAVENDER.append("Marca: "+CBOINSUMO.getSelectedItem()+"\n");
        TEXTAREAVENDER.append("Precio unitario: "+p+"\n");
        TEXTAREAVENDER.append("Cantidad de paquetes adquiridas: "+c+"\n");
        TEXTAREAVENDER.append("Importe: "+imp+"\n");
        TEXTAREAVENDER.append("Descuento: "+dsct+"\n");
        TEXTAREAVENDER.append("Pago Total: "+pgo+"\n");
    }//GEN-LAST:event_BTNVENDERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCERRAR;
    private javax.swing.JButton BTNVENDER;
    private javax.swing.JComboBox<String> CBOINSUMO;
    private javax.swing.JLabel LBLPRECIO;
    private javax.swing.JTextArea TEXTAREAVENDER;
    private javax.swing.JTextField TXTCANTIDAD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
